[32m2024-09-26 18:24:36 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 53c49e03-ebba-48fd-850c-55139bb75005 - 1799048 - LOGS_CAPTURED - Started capturing logs in process (pid: 1799048).
[32m2024-09-26 18:24:36 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 53c49e03-ebba-48fd-850c-55139bb75005 - 1799048 - analytics_cube - STEP_START - Started execution of step "analytics_cube".
[32m2024-09-26 18:24:36 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 53c49e03-ebba-48fd-850c-55139bb75005 - 1799048 - analytics_cube - STEP_OUTPUT - Yielded output "result" of type "Any". (Type check passed).
[32m2024-09-26 18:24:36 -0400[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 53c49e03-ebba-48fd-850c-55139bb75005 - 1799048 - analytics_cube - STEP_FAILURE - Execution of step "analytics_cube" failed.

dagster._core.errors.DagsterExecutionHandleOutputError: Error occurred while handling output "result" of step "analytics_cube"::

dagster._check.functions.CheckError: DuckDBIOManager does not have a handler for type '<class 'str'>'. Has handlers for types '<class 'polars.dataframe.frame.DataFrame'>'. Please build the DuckDBIOManager with an type handler for type '<class 'str'>', so the DuckDBIOManager can correctly handle the output.

Stack Trace:
  File "/home/christianocean/quiv/.venv/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/christianocean/quiv/.venv/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 478, in iterate_with_context
    next_output = next(iterator)
  File "/home/christianocean/quiv/.venv/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 751, in _gen_fn
    gen_output = output_manager.handle_output(output_context, output.value)
  File "/home/christianocean/quiv/.venv/lib/python3.10/site-packages/dagster/_core/storage/db_io_manager.py", line 139, in handle_output
    self._check_supported_type(obj_type)
  File "/home/christianocean/quiv/.venv/lib/python3.10/site-packages/dagster/_core/storage/db_io_manager.py", line 285, in _check_supported_type
    raise CheckError(msg)
[0m
